# code: language=ansible

# ------------------------------------------------------------------------------
# Create Sensitive Directory
# ------------------------------------------------------------------------------
# This task creates the designated directory for storing sensitive security-related files,
# including TLS certificates, private keys, and CA assets.
# It ensures the directory and its parent paths exist before secret generation tasks run.
- name: Create sensitive directory
  file:
    path: "{{ sensitive_directory }}"
    state: directory
    recurse: true

# ------------------------------------------------------------------------------
# Create Container Volume Directory
# ------------------------------------------------------------------------------
# This task creates the directory structure used to persist Docker container volumes.
# These volumes will be mounted into services like PostgreSQL and Consul to store data,
# configurations, and TLS secrets across container restarts.
- name: Create container volumes directory
  file:
    path: "{{ containers_volume_dir }}"
    state: directory
    recurse: true

# ------------------------------------------------------------------------------
# Conditionally Generate Root CA Certificate
# ------------------------------------------------------------------------------
# This task includes the logic required to generate a root CA certificate and key pair.
# If the required CA files already exist, the generation is skipped automatically.
# The resulting CA is used to sign service certificates for Consul, PostgreSQL, and others.
- include_tasks:
    file: "{{ current_dir }}/tasks/security/generate_root_certificate.yml"

# ------------------------------------------------------------------------------
# Setup Consul TLS Certificates
# ------------------------------------------------------------------------------
# This task includes the setup routine for generating and placing the Consul
# service certificates, signed by the root Certificate Authority (CA).
# These certificates enable secure mutual TLS (mTLS) communication between
# Consul agents in the cluster, ensuring encrypted and authenticated service traffic.
- include_tasks:
    file: "{{ current_dir }}/tasks/security/setup_consul_secrets.yml"

# ------------------------------------------------------------------------------
# Setup HAProxy TLS Certificates
# ------------------------------------------------------------------------------
# This task includes the setup routine for provisioning and placing the HAProxy
# certificates required for secure communication with Consul. The certificates
# ensure HAProxy can validate and trust Consul nodes, completing the mTLS setup
# across the service mesh.
- include_tasks:
    file: "{{ current_dir }}/tasks/security/setup_haproxy_secrets.yml"

