# code: language=ansible

# ------------------------------------------------------------------------------
# Create Sensitive Directory
# ------------------------------------------------------------------------------
# This task creates the designated directory for storing sensitive security-related files,
# including TLS certificates, private keys, and CA assets.
# It ensures the directory and its parent paths exist before secret generation tasks run.
- name: Create sensitive directory
  file:
    path: "{{ sensitive_directory }}"
    state: directory
    recurse: true

# ------------------------------------------------------------------------------
# Create Container Volume Directory
# ------------------------------------------------------------------------------
# This task creates the directory structure used to persist Docker container volumes.
# These volumes will be mounted into services like PostgreSQL and Consul to store data,
# configurations, and TLS secrets across container restarts.
- name: Create container volumes directory
  file:
    path: "{{ containers_volume_dir }}"
    state: directory
    recurse: true

# ------------------------------------------------------------------------------
# Conditionally Generate Root CA Certificate
# ------------------------------------------------------------------------------
# This task includes the logic required to generate a root CA certificate and key pair.
# If the required CA files already exist, the generation is skipped automatically.
# The resulting CA is used to sign service certificates for Consul, PostgreSQL, and others.
- include_tasks:
    file: "{{ current_dir }}/tasks/security/generate_root_certificate.yml"

# ------------------------------------------------------------------------------
# Setup Consul TLS Certificates
# ------------------------------------------------------------------------------
# This task includes the setup routine for generating and placing the Consul service certificate,
# signed by the root CA. It prepares Consul for mTLS-secured communication in the cluster.
- include_tasks:
    file: "{{ current_dir }}/tasks/security/setup_consul_secrets.yml"
