# code: language=ansible

# ------------------------------------------------------------------------------
# Copy Consul TLS Configuration to Each Node
# ------------------------------------------------------------------------------
# This task copies the static TLS configuration file (`tls.hcl`) into the configuration
# directory of each Consul server node. The file defines the parameters required
# to enable encrypted communication via HTTPS and encrypted gossip using mTLS.
- name: Copy consul configuration
  copy:
    src: "{{ current_dir }}/files/consul/tls.hcl"
    dest: "{{ consul_config_path }}/server_{{ item }}/tls.hcl"
    mode: "0644"
  loop: "{{ range(1, (consul_cluster_replica_count | default(3)) + 1) }}"

# ------------------------------------------------------------------------------
# Copy Consul Container Dockerfile
# ------------------------------------------------------------------------------
# This task copies the Dockerfile used to build the custom Consul container image.
# The Dockerfile defines runtime behaviors, installs the Consul binary, and
# enforces best practices such as non-root execution and TLS support.
- name: Copy consul docker file
  copy:
    src: "{{ current_dir }}/files/containers/Dockerfile.consul"
    dest: "{{ containers_dir }}/Dockerfile.consul"
    mode: "0644"